import type { Metadata } from "next";
import { Sora, Manrope } from "next/font/google";
import "./globals.css";
import AppKitProvider from "@/src/components/appkit";
import { Toaster } from "react-hot-toast";

// Sora font (optional – for headings, accents)
const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sora",
});

// Manrope font (main font)
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Degen Duel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${sora.variable} ${manrope.variable}`}
      >
        <AppKitProvider>
          <Toaster />
          {children}
        </AppKitProvider>
      </body>
    </html>
  );
}
