import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import AppKitProvider from "@/src/components/appkit";
import { Toaster } from "react-hot-toast";

// Import Sora font from Google Fonts
const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "Degen Duel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <AppKitProvider>
          <Toaster />
          {children}
        </AppKitProvider>
      </body>
    </html>
  );
}
